### ISSUE TITLE
Sample from learned variables directly

### ISSUE THREAD

**Issue by charstnut** [numericalEFT/MCIntegration.jl#34]
Hi,

Thanks for making this library for integration. I'm wondering if it's possible to sample from the learned variables (in the `Configuration`) directly? This would be helpful to evaluate other quantities that depend on the variable distribution after the integration and optimization is done. It would also be helpful to output the pdf of the optimized variables.

Best,
Charles

**Comment by kunyuan** [comment]
Hi Charles,

Thank you for asking! I hope our package is helpful to you.

You can sample from the learned variables. To do this, in the second run of ``MCIntegration.integrate``, you need to set the argument ``var = result.config.var``, where ``result`` is the return value of the previous integrate call. I demonstrate the idea in the following figure. You can see the second run starts with much less noise.

<img width="968" alt="Screen Shot 2022-12-16 at 4 34 18 PM" src="https://user-images.githubusercontent.com/2466956/208192726-2e185f76-01bb-4b92-a8b5-a8553adeea22.png">

If there are multiple types of variables and you only need one of them, you can pick that one from ``result.config.var``, then use it to build a new set of variables for your new integral.

 You can also access the learned distribution of the i-th variable using ``result.config.var[i].histogram``. We don't have a built-in function to output it yet.

It is definitely a good idea to give an example in the tutorial on how to reuse the learned variables. 

Best,
Kun

**Comment by charstnut** [comment]
Hi Kun,

Thank you for the prompt answer!
Is the following output reasonable for the demo problem? I am plotting the learned histogram but it seems to be uniform.

```
using MCIntegration

res = integrate((x, c) -> log(x[1]) / sqrt(x[1]))
plot(res.config.var[1].histogram)
```

![picture](https://user-images.githubusercontent.com/36014603/208197454-c6e1316f-abb8-4650-a1ab-878a7320a770.png)

**Comment by kunyuan** [comment]
Hi Charles,

     My bad. The variable ``Continuous``, finds the optimal grid to make the measured histogram as flat as possible. So you can plot ``result.config.var[1].grid`` instead. In the following figure, the x-axis is the index of the optimized grid, the y-axis is the actual grid point. 

<img width="587" alt="Screen Shot 2022-12-16 at 5 16 39 PM" src="https://user-images.githubusercontent.com/2466956/208205411-98e973de-5be8-4452-b5f6-5d191753c4bd.png">

BTW: Right now, the ``result.config.var[1].histogram`` is set to ~0 after the integration. That's why you find it is all 10^-10. We probably should keep the histogram information in the next release. 

best,
Kun

**Comment by charstnut** [comment]
Hi Kun,

Perfect! Thanks a lot. With the grid information I should be able to convert it to a sampler with interpolation.

Best,
Charles
