### ISSUE TITLE
Fail to deal with integrands with singularities: a simple case

### ISSUE THREAD

**Issue by phyjswang** [numericalEFT/MCIntegration.jl#52]
Dear Prof. Chen,

Recently I am working on the following integration, where the integrand has a singularity at $x=2$. It turns out that both your package and the standard 1D numerical integration package `QuadGK.jl` fail to deal with it.

```julia
using MCIntegration
using SpecialFunctions
using QuadGK

z0(x) = 2 ≤ x ≤ 3 ? 3 + 2√(3 - x) - (x / 2)^2 : 4 * √(3 - x)
z1(x) = 2 ≤ x ≤ 3 ? 4 * √(3 - x) : 3 + 2 * √(3 - x) - (x / 2)^2
dos(x) = 1 / (√(z0(x)) * π^2) * ellipk(z1(x) / z0(x))

f_integrand(x, c) = dos(x[1])
rslt1 = integrate(f_integrand, var=Continuous(-6, 2 - 1e-5)) # return error
quadgk(dos, -6, 2 - 1e-5) # return error
```

As a workaround, one can skip this singular point manually by separating the integration regime into several parts if necessary. Thus a naive way to make such kind of integration to work is by adding a key word argument specifying the points to be excluded in the integration. However, I guess there must be better ways to deal with this problem, at a more fundamental level relating to the algorithms used.

BTW, I've checked that this integration can be perfectly done in commercial softwares like _Mathematica_.

Best,
Junsen Wang

**Comment by kunyuan** [comment]
It looks like the integrand can not handle the upper bound 2-1e-5, see the attached figure. 
<img width="215" alt="Screenshot 2023-12-02 at 6 18 57 PM" src="https://github.com/numericalEFT/MCIntegration.jl/assets/2466956/9084b2f6-3732-4df5-954a-822cd62a5093">

This problem seems to be an overflow problem associated with "ellipk(1.0)".
